/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import ca.johannes.externalExecute.fileSystem.CreateFileTest;
	import ca.johannes.externalExecute.fileSystem.ReadFileTest;
	import ca.johannes.externalExecute.fileSystem.WriteFileTest;
	
	import flash.display.Sprite;
	import ca.johannes.externalExecute.fileSystem.CopyFileTest;
	import ca.johannes.externalExecute.fileSystem.MoveFileTest;
	import ca.johannes.externalExecute.fileSystem.DeleteFileTest;
	import ca.johannes.externalExecute.fileSystem.CreateDirectoryTest;
	import ca.johannes.externalExecute.fileSystem.DeleteDirectoryTest;
	import ca.johannes.externalExecute.fileSystem.DeleteDirectoryContentsTest;
	import ca.johannes.externalExecute.fileSystem.ListDirectoryContentsTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var ca_johannes_externalExecute_fileSystem_ListDirectoryContentsTest_obj:ca.johannes.externalExecute.fileSystem.ListDirectoryContentsTest;
		private var ca_johannes_externalExecute_fileSystem_DeleteDirectoryContentsTest_obj:ca.johannes.externalExecute.fileSystem.DeleteDirectoryContentsTest;
		private var ca_johannes_externalExecute_fileSystem_DeleteDirectoryTest_obj:ca.johannes.externalExecute.fileSystem.DeleteDirectoryTest;
		private var ca_johannes_externalExecute_fileSystem_DeleteFileTest_obj:ca.johannes.externalExecute.fileSystem.DeleteFileTest;
		private var ca_johannes_externalExecute_fileSystem_CreateDirectoryTest_obj:ca.johannes.externalExecute.fileSystem.CreateDirectoryTest;
		private var ca_johannes_externalExecute_fileSystem_MoveFileTest_obj:ca.johannes.externalExecute.fileSystem.MoveFileTest;
		
		private var ca_johannes_externalExecute_fileSystem_ReadFileTest_obj:ca.johannes.externalExecute.fileSystem.ReadFileTest;
		private var ca_johannes_externalExecute_fileSystem_CopyFileTest_obj:ca.johannes.externalExecute.fileSystem.CopyFileTest;
		private var ca_johannes_externalExecute_fileSystem_WriteFileTest_obj:ca.johannes.externalExecute.fileSystem.WriteFileTest;
		private var ca_johannes_externalExecute_fileSystem_CreateFileTest_obj:ca.johannes.externalExecute.fileSystem.CreateFileTest;
	}
}